version: '2'

services:
  pade:
    build:
      context: .
      dockerfile: ./docker/DockerfileDev
    ports:
      - "5000:5000"
      - "8000:8000"
      - "8001:8001"
      - "3000:3000"
    volumes:
      - ./app/:/app